# Generated by Django 5.2.4 on 2025-07-22 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('legal_app', '0005_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Advisor',
            fields=[
                ('email', models.CharField(max_length=60, primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=45)),
                ('name', models.CharField(max_length=60)),
                ('qualification', models.CharField(max_length=100)),
                ('gender', models.CharField(max_length=6)),
                ('expirience', models.TextField()),
                ('service_type', models.CharField(max_length=100)),
                ('about_advisor', models.TextField()),
                ('profile_pic', models.FileField(default='', upload_to='advisor_pic/')),
            ],
        ),
    ]
