# Generated by Django 5.2.4 on 2025-07-27 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('legal_app', '0006_advisor'),
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('service_type', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('description', models.TextField(default='')),
                ('service_pic', models.FileField(default='', upload_to='service_pic/')),
            ],
        ),
    ]
