# Generated by Django 5.2.4 on 2025-07-29 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('legal_app', '0007_service'),
    ]

    operations = [
        migrations.AddField(
            model_name='advisor',
            name='phone',
            field=models.CharField(default='9898989898', max_length=15),
        ),
    ]
